name: trippo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_direction: ^0.0.5
  bloc_concurrency: ^0.2.0
  bot_toast: ^4.0.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  draggable_home: ^1.0.2
  equatable: ^2.0.3
  extended_image: ^6.0.3
  extended_nested_scroll_view: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_blurhash: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_lorem: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_reorderable_list: ^1.2.0
  flutter_sequence_animation: ^4.0.0-nullsafety
  flutter_staggered_grid_view: ^0.4.0
  flutter_sticky_header: ^0.6.1
  flutter_svg: ^1.0.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.3
  http: ^0.13.4
  image_cropper: ^2.0.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  loading_animation_widget: ^1.1.0+5
  location: ^4.4.0
  material_floating_search_bar: ^0.3.7
  scroll_to_index: ^2.1.1
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  sliding_clipped_nav_bar: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  sticky_headers: ^0.2.0
  stream_transform: ^2.0.0
  url_launcher: ^6.1.5
  bloc_concurrency: ^0.2.0
  flutter_holo_date_picker: ^1.0.6
  photo_view: ^0.14.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
    - assets/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: NotoNaskhArabic
      fonts:

        - asset: assets\fonts\NotoNaskhArabic-Medium.ttf
          weight: 300
          style: normal

        - asset: assets\fonts\NotoNaskhArabic-Regular.ttf
          weight: 400
          style: normal

        - asset: assets\fonts\NotoNaskhArabic-SemiBold.ttf
          weight: 500
          style: normal

        - asset: assets\fonts\NotoNaskhArabic-Bold.ttf
          weight: 700
          style: normal

    - family: Sf-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 200
          style: normal

        - asset: assets/fonts/SF-Pro-Display-light.otf
          weight: 300
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
          style: normal

        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 900
          style: normal

    - family: TrippoIcons
      fonts:
        - asset: assets/icons/TrippoIcons.ttf
